# https://gohugo.io/getting-started/configuration/
baseURL: https://ryosan-470.github.io/
defaultContentLanguage: ja
enableEmoji: true
enableGitInfo: true # Ref: https://gohugo.io/variables/git/
hasCJKLanguage: true
permalinks:
  posts: /posts/:year/:month/:day/:filename
publishDir: docs
theme: beautifulhugo
title: ryosan-470 Blog

params:
  author:
    name: ryosan-470
  mainSections:
    - posts
  commit: true
  rss: true
  comments: true
  readingTime: false
  wordCount: false
  socialShare: true
  showRelatedPosts: false
  useHLJS: true
  delayDisqus: true
author:
  name: ryosan-470
  github: ryosan-470
  twitter: ryosan470

menu:
  main:
  - name: Blog
    url: posts
    weight: 3
  - name: Tags
    url: tags
    weight: 2
  - name: About
    url: about
    weight: 1
