# https://gohugo.io/getting-started/configuration/
baseURL: https://ryosan-470.github.io/
defaultContentLanguage: ja
enableEmoji: true
enableGitInfo: true # Ref: https://gohugo.io/variables/git/
hasCJKLanguage: true
permalinks:
  posts: /posts/:year/:month/:day/:filename
publishDir: docs
theme: beautifulhugo
title: ryosan-470 Blog

params:
  author:
    name: ryosan-470
  mainSections:
    - posts
  # https://github.com/halogenica/beautifulhugo/tree/master?tab=readme-ov-file#disqus-support
  commit: "https://github.com/ryosan-470/ryosan-470.github.io/tree/"
  rss: true
  comments: true
  readingTime: false
  wordCount: false
  socialShare: true
  showRelatedPosts: false
  # https://github.com/halogenica/beautifulhugo/tree/master?tab=readme-ov-file#disqus-support
  useHLJS: true
  delayDisqus: true

menu:
  main:
  - name: Blog
    url: posts
    weight: 3
  - name: Tags
    url: tags
    weight: 2
  - name: About
    url: about
    weight: 1

# theme の設定
# https://github.com/halogenica/beautifulhugo/tree/master?tab=readme-ov-file#disqus-support
author:
  name: ryosan-470
  github: ryosan-470
  twitter: ryosan470

services:
  # https://gohugo.io/templates/internal/#disqus
  disqus:
    shortname: ryosan-470
  # https://gohugo.io/templates/internal/#google-analytics
  googleAnalytics:
    ID: G-0P8G9JQ28X
